BulkyBook/BulkyBook/Areas/Customer/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Options;
using Stripe;
using Twilio;
using Twilio.Rest.Api.V2010.Account;

namespace BulkyBook.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class CartController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IEmailSender _emailSender;

        private TwilioSettings _twilioOptions { get; set; }

        [BindProperty]
        public ShoppingCartViewModel ShoppingCartViewModel { get; set; }
        public CartController(IUnitOfWork unitOfWork, IEmailSender emailSender, UserManager<IdentityUser> userManager, IOptions<TwilioSettings> twilioPtions)
        {
            _userManager = userManager;
            _unitOfWork = unitOfWork;
            _emailSender = emailSender;
            _twilioOptions = twilioPtions.Value;

        }
        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            ShoppingCartViewModel = new ShoppingCartViewModel()
            {
                OrderHeader = new OrderHeader(),
                ListCart = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value, includeProperties: "Product")
            };

            ShoppingCartViewModel.OrderHeader.OrderTotal = 0;
            ShoppingCartViewModel.OrderHeader.ApplicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == claim.Value, includeProperties: "Company");


            foreach (var list in ShoppingCartViewModel.ListCart)
            {
                list.Price = Constants.GetPriceBasedOnQuanitity(list.Count, list.Product.Price, list.Product.Price50, list.Product.Price100);
                ShoppingCartViewModel.OrderHeader.OrderTotal += list.Price * list.Count;
                list.Product.Description = Constants.ConvertHtmlToText(list.Product.Description);
                if (list.Product.Description.Length > 150)
                {
                    list.Product.Description = list.Product.Description.Substring(0, 149) + "...";
                }
            }


            return View(ShoppingCartViewModel);
        }

        [HttpPost]
        [ActionName("Index")]
        public async Task<IActionResult> IndexPost()
        {

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var user = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == claim.Value);

            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "Verification email is empty");
            }



            var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
            code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
            var callbackUrl = Url.Page(
                "/Account/ConfirmEmail",
                pageHandler: null,
                values: new { area = "Identity", userId = user.Id, code = code },
                protocol: Request.Scheme);

            await _emailSender.SendEmailAsync(user.Email, "Confirm your email",
                $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");

            ModelState.AddModelError(string.Empty, "Verification email sent, Please check your email.");
            return RedirectToAction("Index");
        }


        public IActionResult Plus(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(c => c.Id == cartId, includeProperties: "Product");
            cart.Count++;
            cart.Price = Constants.GetPriceBasedOnQuanitity(cart.Count, cart.Product.Price, cart.Product.Price50, cart.Product.Price100);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Index));

        }

        public IActionResult Minus(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(c => c.Id == cartId, includeProperties: "Product");
            if (cart.Count == 1)
            {
                var count = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == cart.ApplicationUserId).ToList().Count();
                _unitOfWork.ShoppingCart.Remove(cart);
                _unitOfWork.Save();
                HttpContext.Session.SetInt32(Constants.ssShoppingCart, count - 1);
            }
            else
            {
                cart.Count--;
                cart.Price = Constants.GetPriceBasedOnQuanitity(cart.Count, cart.Product.Price, cart.Product.Price50, cart.Product.Price100);
                _unitOfWork.Save();

            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(c => c.Id == cartId, includeProperties: "Product");
            var count = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == cart.ApplicationUserId).ToList().Count();
            _unitOfWork.ShoppingCart.Remove(cart);
            _unitOfWork.Save();
            HttpContext.Session.SetInt32(Constants.ssShoppingCart, count - 1);

            return RedirectToAction(nameof(Index));


        }

        public IActionResult Summary()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            ShoppingCartViewModel = new ShoppingCartViewModel()
            {
                OrderHeader = new OrderHeader(),
                ListCart = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == claim.Value, includeProperties: "Product")
            };

            ShoppingCartViewModel.OrderHeader.ApplicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == claim.Value, includeProperties: "Company");

            foreach (var list in ShoppingCartViewModel.ListCart)
            {
                list.Price = Constants.GetPriceBasedOnQuanitity(list.Count, list.Product.Price, list.Product.Price50, list.Product.Price100);
                ShoppingCartViewModel.OrderHeader.OrderTotal += list.Price * list.Count;
            }
            ShoppingCartViewModel.OrderHeader.Name = ShoppingCartViewModel.OrderHeader.ApplicationUser.Name;
            ShoppingCartViewModel.OrderHeader.PhoneNumber = ShoppingCartViewModel.OrderHeader.ApplicationUser.PhoneNumber;
            ShoppingCartViewModel.OrderHeader.StreetAddress = ShoppingCartViewModel.OrderHeader.ApplicationUser.StreetAddress;
            ShoppingCartViewModel.OrderHeader.City = ShoppingCartViewModel.OrderHeader.ApplicationUser.City;
            ShoppingCartViewModel.OrderHeader.State = ShoppingCartViewModel.OrderHeader.ApplicationUser.State;
            ShoppingCartViewModel.OrderHeader.PostalCode = ShoppingCartViewModel.OrderHeader.ApplicationUser.PostalCode;

            return View(ShoppingCartViewModel);
        }

        [HttpPost]
        [ActionName("Summary")]
        [ValidateAntiForgeryToken]
        public IActionResult SummaryPost(string stripeToken)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            ShoppingCartViewModel.OrderHeader.ApplicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == claim.Value, includeProperties: "Company");

            ShoppingCartViewModel.ListCart = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == claim.Value, includeProperties: "Product");
            ShoppingCartViewModel.OrderHeader.PaymentStatus = Constants.PaymentStatusPending;
            ShoppingCartViewModel.OrderHeader.OrderStatus = Constants.StatusPending;
            ShoppingCartViewModel.OrderHeader.ApplicationUserId = claim.Value;
            ShoppingCartViewModel.OrderHeader.OrderDate = DateTime.Now;

            _unitOfWork.OrderHeader.Add(ShoppingCartViewModel.OrderHeader);
            _unitOfWork.Save();

            foreach (var item in ShoppingCartViewModel.ListCart)
            {
                item.Price = Constants.GetPriceBasedOnQuanitity(item.Count, item.Product.Price, item.Product.Price50, item.Product.Price100);
                OrderDetails orderDetails = new OrderDetails()
                {
                    ProductId = item.ProductId,
                    OrderId = ShoppingCartViewModel.OrderHeader.Id,
                    Price = item.Price,
                    Count = item.Count
                };
                ShoppingCartViewModel.OrderHeader.OrderTotal += orderDetails.Count * orderDetails.Price;
                _unitOfWork.OrderDetails.Add(orderDetails);
            }

            _unitOfWork.ShoppingCart.RemoveRange(ShoppingCartViewModel.ListCart);
            _unitOfWork.Save();
            HttpContext.Session.SetInt32(Constants.ssShoppingCart, 0);

            if (stripeToken == null)
            {
                //order will be created for delayed payment for authorized company
                ShoppingCartViewModel.OrderHeader.PaymentDueDate = DateTime.Now.AddDays(30);
                ShoppingCartViewModel.OrderHeader.PaymentStatus = Constants.PaymentStatusDelayedPayment;
                ShoppingCartViewModel.OrderHeader.OrderStatus = Constants.StatusApproved;
            }
            else
            {

BulkyBook/BulkyBook/Areas/Customer/Views/Cart/Index.cshtml
@model ShoppingCartViewModel

<form method="post">
    <br />
    @if (Model.ListCart.Count() > 0)
    {
        <div class="backgroundWhiteBorder">
            <div class="container">
                <div class="card">
                    <div class="card-header bg-dark text-light ml-0 row container">
                        <div class="col-6">
                            <i class="fa fa-shopping-cart"></i> &nbsp;
                            Shopping Cart
                        </div>
                        <div class="col-6 text-right">
                            <a asp-area="Customer" asp-controller="Home" asp-action="Index" class="btn btn-outline-info btn-sm">Continue Shopping</a>
                        </div>
                    </div>


                    <div class="card-body">
                        @foreach (var item in Model.ListCart)
                        {
                            <div class="row">
                                <div class="d-none d-lg-block col-lg-2 text-center py-2">
                                    <img src="@item.Product.ImageUrl" class="rounded" style="max-height:140px;max-width:140px" />
                                </div>
                                <div class="col-12 text-sm-center col-lg-5 text-lg-left">
                                    <h5><strong>@item.Product.Title</strong></h5>
                                    <p><small>@item.Product.Description</small></p>
                                </div>
                                <div class="col-12 text-sm-center col-lg-5 text-lg-right row">
                                    <div class="col-4 text-md-right" style="padding-top:5px;">
                                        <h6><strong>@item.Price &#8382;<span class="text-muted"> x </span>@item.Count </strong></h6>
                                    </div>
                                    <div class="col-6 col-sm-4 col-lg-6">
                                        <div class="float-right mx-1">
                                            <a asp-action="Plus" asp-route-cartId="@item.Id" type="submit" class="btn btn-primary">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                        </div>
                                        <div class="float-right mx-1">
                                            <a asp-action="Minus" asp-route-cartId="@item.Id" type="submit" class="btn btn-danger">
                                                <i class="fas fa-minus"></i>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-2 col-sm-4 col-lg-2 text-right">
                                        <a asp-action="Remove" asp-route-cartId="@item.Id" type="submit" class="btn btn-outline-danger">
                                            <i class="fas fa-trash"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                            <hr />

                        }

                        <div class="row">
                            <div class="col-12 col-md-6 offset-md-6 col-lg-4 offset-lg-8 pr-4">
                                <ul class="list-group">
                                    <li class="list-group-item d-flex justify-content-between bg-primary">
                                        <span> Total (GEL)</span>
                                        <strong>@Model.OrderHeader.OrderTotal.ToString("0.00") &#8382;<span id="txtOrderTotal"></span></strong>
                                    </li>
                                </ul>
                            </div>
                        </div>

                    </div>



                    <div class="card-footer">
                        <div class="card-footer row">
                            @if (!Model.OrderHeader.ApplicationUser.EmailConfirmed &&
Model.OrderHeader.ApplicationUser.CompanyId != null &&
Model.OrderHeader.ApplicationUser.Company.IsAuthorizedCompany)
                            {
                                <div class="col-8 text-danger">
                                    Email Must be confirmed for authorized customers!
                                </div>
                                <div class="col-4">
                                    <button type="submit" class="btn btn-outline-warning btn-sm">Click here to resend confirmation email</button>
                                </div>
                            }
                            else
                            {
                                <div class="col-sm-12 col-lg-4 col-md-6 offset-lg-8 offset-md-6 ">

                                    <a asp-area="Customer" asp-controller="Cart" asp-action="Summary" class="btn btn-success form-control">Summary</a>
                                </div>
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="row">
            <div class="col-4 offset-4">
                <ul>
                    <li class="list-group-item d-flex bg-primary">
                        There are no items in shopping cart
                    </li>
                </ul>
            </div>
        </div>

    }
</form>

BulkyBook/BulkyBook/Areas/Customer/Views/Cart/OrderConfirmation.cshtml
@model int

<div class="container row">
    <div class="col-12 text-center">
        <h1 class="text-primary text-center">Order Submitted Successfully</h1><br />
        <img src="~/images/lawn_leaf.jpg" width="50%" />
    </div>
    <div class="col-12 text-center" style="color:green">
        <br />
        Thank you for your order! <br />
        We have received your order and we will send a follow up email shortly!
        <br />
        Your Order Number is : @Model
    </div>
</div>

BulkyBook/BulkyBook/Areas/Customer/Views/Cart/Summary.cshtml
@model ShoppingCartViewModel
@using Microsoft.Extensions.Options
@inject IOptions<BulkyBook.Utility.StripeSettings> Stripe


<form method="post">
    <br />
    <div class="backgroundWhiteBorder">
        <div class="container">
            <div class="card">
                <div class="card-header bg-dark text-light ml-0 row container">
                    <div class="col-6">
                        <i class="fa fa-shopping-cart"></i> &nbsp;
                        Order Summary
                    </div>
                    <div class="col-6 text-right">
                        <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="btn btn-outline-info btn-sm">Back to Cart</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="container rounded p-2">
                        <div class="row">
                            <div class="col-12 col-lg-6 pb-4">
                                <div class="row">
                                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                                        <span class="text-info">PickUp Details:</span>
                                    </h4>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label asp-for="OrderHeader.Name">Name</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="OrderHeader.Name" type="text" class="form-control" />
                                        <span asp-validation-for="OrderHeader.Name" class="text-warning"></span>
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label asp-for="OrderHeader.PhoneNumber">Phone</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="OrderHeader.PhoneNumber" type="text" class="form-control" />
                                        <span asp-validation-for="OrderHeader.PhoneNumber" class="text-warning"></span>
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label asp-for="OrderHeader.StreetAddress">Street Address</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="OrderHeader.StreetAddress" type="text" class="form-control" />
                                        <span asp-validation-for="OrderHeader.StreetAddress" class="text-warning"></span>

                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label asp-for="OrderHeader.City">City</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="OrderHeader.City" type="text" class="form-control" />
                                        <span asp-validation-for="OrderHeader.City" class="text-warning"></span>
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label asp-for="OrderHeader.State">State</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="OrderHeader.State" type="text" class="form-control" />
                                        <span asp-validation-for="OrderHeader.State" class="text-warning"></span>
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-3">
                                        <label asp-for="OrderHeader.PostalCode">Postal Code</label>
                                    </div>
                                    <div class="col-9">
                                        <input asp-for="OrderHeader.PostalCode" type="text" class="form-control" />
                                        <span asp-validation-for="OrderHeader.PostalCode" class="text-warning"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-12 col-lg-5 offset-lg-1">
                                <h4 class="d-flex justify-content-between align-items-center mb-3">
                                    <span class="text-info">Order Summary:</span>
                                </h4>
                                <ul class="list-group mb-3">
                                    @foreach (var item in Model.ListCart)
                                    {
                                        <li class="list-group-item d-flex justify-content-between">
                                            <div>
                                                <h6 class="my-0">@item.Product.Title</h6>
                                                <small class="text-muted">Quantity: @item.Count</small>
                                            </div>
                                            <span> @((item.Product.Price*item.Count).ToString("0.00")) &#8382;</span>
                                        </li>
                                    }

                                    <li class="list-group-item d-flex justify-content-between bg-primary">
                                        <small>Total:</small>
                                        <strong>@Model.OrderHeader.OrderTotal.ToString("0.00") &#8382;</strong>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col-12 col-md-8 pt-2">
                            <p style="color:orange; font-size:14px;">Estimate Arrival Date: @DateTime.Now.AddDays(7).ToShortDateString() - @DateTime.Now.AddDays(14).ToShortDateString()</p>
                        </div>
                        <div class="col-12 col-md-4">

                            @{
                                var OrderToTalForStripe = Model.OrderHeader.OrderTotal * 100;
                            }
                            @if (Model.OrderHeader.ApplicationUser.Company == null || !Model.OrderHeader.ApplicationUser.Company.IsAuthorizedCompany)
                            {
                                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                        data-key="@Stripe.Value.PublishableKey"
                                        data-amount=@OrderToTalForStripe
                                        data-name="Vazha's Book Store"
                                        data-label="Place Order"
                                        data-description="Good Books"
                                        data-locale="auto"
                                        data-allow-remember-me="false"
                                        data-image="https://stripe.com/img/documentation/checkout/marketplace.png">
                                </script>
                                <script>
                                    document.getElementsByClassName("stripe-button-el")[0].style.display = 'none';
                                </script>
                                <button type="submit" value="Place Order" class="btn btn-success form-control">Place Order</button>
                            }
                            else
                            {
                                <button type="submit" value="Place Order" class="btn btn-primary form-control">Place Order</button>
                            }


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}